spring:
  cloud:
    gateway:
      routes:
        - id: JOB-MS
          uri: lb://JOB-MS-DEV
          predicates:
            - Path=/job/**

        - id: EUREKA-SERVER
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/


        - id: EUREKA-SERVER-STATIC
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**







  application:
    name: ApiGateway

server:
  port: 9898

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
